# Generated by Django 4.2.20 on 2025-03-24 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.JSONField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
